/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kr.disdong.lib.template

class Library {
    fun someLibraryMethod(): Boolean {
        println("jello world")
        return true
    }
}
